first_project/first_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('polls/', include('polls.urls')),
    path('routing/', include('routing_lesson.urls')),
    path('polls_class/', include('polls_class.urls')),
]

first_project/polls/urls.py
from django.urls import path, include
from . import views

app_name = 'polls'
urlpatterns = [
    path('', views.index, name='index'),
    path('<int:question_id>/', views.detail, name='detail'),
    path('<int:question_id>/results/', views.results, name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
    path('api/v1/questions/<int:pk>/', views.question_element, name='GET question <id>'),
    path('api/v1/questions/', views.question_collection, name='GET questions'),
    path('accounts/', include('django.contrib.auth.urls'))
]

first_project/polls_class/urls.py
from django.urls import path
from . import views

app_name = 'polls_class'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('<int:pk>/', views.DetailView.as_view(), name='detail'),
    path('<int:pk>/results/', views.ResultsView.as_view(), name='results'),
    path('<int:question_id>/vote/', views.vote, name='vote'),
]

first_project/routing_lesson/urls.py
from django.urls import path, re_path
from . import views


urlpatterns = [
    path('', views.index, name='index'),
    path('articles/2003/', views.special_case_2003, name='special'),
    re_path(r'^articles/(?P<year>[0-9]{4})/$', views.year_archive, name='years_archive'),
    path('articles/<int:year>/<int:month>/', views.month_archive, name='month_archive'),
    path('articles/<int:year>/<int:month>/<slug:slug>/', views.article_detail, name='articles_archive'),
]
# str "/" - exclude
# int 0, 1, ... (>=0)
# slug - ASCII char + number + - + _
# uuid - UUID format
# path - include "/"

# reverse
# reverse_lazy



first_project/polls/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return f"question {self.id}: {self.question_text}"


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f"answer {self.id}: {self.choice_text}"



first_project/polls_class/models.py
from django.db import models


class Question(models.Model):
    question_text = models.CharField(max_length=200)
    pub_date = models.DateTimeField('date published')

    def __str__(self):
        return f"question {self.id}: {self.question_text}"


class Choice(models.Model):
    question = models.ForeignKey(Question, on_delete=models.CASCADE)
    choice_text = models.CharField(max_length=200)
    votes = models.IntegerField(default=0)

    def __str__(self):
        return f"answer {self.id}: {self.choice_text}"

first_project/routing_lesson/models.py
from django.db import models



first_project/polls/views.py
from django.http import HttpResponse, HttpRequest, HttpResponseRedirect
# from django.template import loader
from django.shortcuts import render, get_object_or_404
from django.http import Http404
from django.urls import reverse
from rest_framework.decorators import api_view
from rest_framework.response import Response

from .models import Question, Choice
from .serializers import QuestionSerializer


@api_view(['GET'])
def question_collection(request):
    if request.method == 'GET':
        quests = Question.objects.all()
        serializer = QuestionSerializer(quests, many=True)
        return Response(serializer.data)

@api_view(['GET'])
def question_element(request, pk):
    try:
        post = Question.objects.get(pk=pk)
    except Question.DoesNotExist:
        return HttpResponse(status=404)

    if request.method == 'GET':
        serializer = QuestionSerializer(post)
        return  Response(serializer.data)


def index(request: HttpRequest) -> HttpResponse:
    """Виводить список останніх опитувань"""
    latest_question_list = Question.objects.order_by("-pub_date")[:5]
    context = {"latest_question_list": latest_question_list}
    return render(request, "polls/index.html", context)


def detail(request: HttpRequest, question_id) -> HttpResponse:
    """Виводить деталізацію для конкретного одного опитування"""
    question = get_object_or_404(Question, pk=question_id)
    return render(request, "polls/details.html", {"question": question})


def results(request: HttpRequest, question_id) -> HttpResponse:
    """Тут повинні бути результати з голосування по конкретному питанню"""
    question = get_object_or_404(Question, pk=question_id)
    return render(request, 'polls/results.html', {'question': question})


def vote(request: HttpRequest, question_id) -> HttpResponse:
    """Сторінка де можна проголосувати за конкретное питання"""
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            'polls/detail.html',
            {
                'question': question,
                'error_message': "Ви не обрали відповідь!"
            }
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

first_project/polls_class/views.py
from django.shortcuts import render, get_object_or_404
from django.http import HttpResponseRedirect, HttpRequest, HttpResponse
from django.urls import reverse
from django.views import generic

from . models import Question, Choice

class IndexView(generic.ListView):
    template_name = "polls/index.html"
    context_object_name = "latest_question_list"

    def get_queryset(self):
        """Return the last five published questions"""
        return Question.objects.order_by("-pub_date")[:5]


class DetailView(generic.DetailView):
    model = Question
    template_name = "polls/detail.html"


class ResultsView(generic.DetailView):
    model = Question
    template_name = "polls/results.html"


def vote(request: HttpRequest, question_id) -> HttpResponse:
    """Сторінка де можна проголосувати за конкретное питання"""
    question = get_object_or_404(Question, pk=question_id)
    try:
        selected_choice = question.choice_set.get(pk=request.POST['choice'])
    except (KeyError, Choice.DoesNotExist):
        return render(
            request,
            'polls/detail.html',
            {
                'question': question,
                'error_message': "Ви не обрали відповідь!"
            }
        )
    else:
        selected_choice.votes += 1
        selected_choice.save()
        return HttpResponseRedirect(reverse('polls:results', args=(question.id,)))

first_project/routing_lesson/views.py
from django.http import HttpResponse, HttpRequest


def index(request: HttpRequest) -> HttpResponse:
    return  HttpResponse("it is start page")


def special_case_2003(request: HttpRequest) -> HttpResponse:
    return HttpResponse("special case 2003")


def year_archive(request: HttpRequest, year) -> HttpResponse:
    return HttpResponse(f"year archive - {year}")


def month_archive(request: HttpRequest, year, month) -> HttpResponse:
    return HttpResponse(f"month archive - year: {year}, month: {month}")


def article_detail(request: HttpRequest, year, month, slug) -> HttpResponse:
    return HttpResponse(f"article detail:\nyear: {year}\nmonth: {month}\nslug: {slug}")

first_project/polls/templates/base.html
<!--polls/templates/base.html-->

<style>
    label, input {
        display: block;
    }
    span.helptext {
        display: none;
    }
</style>

<h1>Опитування:</h1>

{% block content %}
{% endblock %}

first_project/polls/templates/polls/details.html
<form action="{% url 'polls:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% for choice in question.choice_set.all %}
    <p>
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ choice.id }}">
    <label for="choice{{forloop.counter}}">{{ choice.choice_text }}</label>
    </p>
    {% endfor %}

</fieldset>
<input type="submit" value="Vote">
</form>

first_project/polls/templates/polls/index.html
{% extends 'base.html' %}

{% block content %}

Hello, {{ user.username|default:'Guest'}}!

<div>
    {% if user.is_authenticated %}
        <a href="{% url 'polls:logout' %}">Logout</a>
        <a href="{% url 'polls:password_change' %}">Change password</a>
    {% else %}
        <a href="{% url 'polls:login' %}">Login</a>
    {% endif %}
</div>

{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

{% endblock %}

first_project/polls/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} ---> {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls:detail' question.id %}">Vote again?</a>

first_project/polls_class/templates/polls/details.html
<form action="{% url 'polls_class:vote' question.id %}" method="post">
{% csrf_token %}
<fieldset>
    <legend><h1>{{ question.question_text }}</h1></legend>
    {% if error_message %}<p><strong>{{ error_message }}</strong></p>{% endif %}

    {% for choice in question.choice_set.all %}
    <p>
        <input type="radio" name="choice" id="choice{{forloop.counter}}" value="{{ choice.id }}">
    <label for="choice{{forloop.counter}}">{{ choice.choice_text }}</label>
    </p>
    {% endfor %}

</fieldset>
<input type="submit" value="Vote">
</form>

first_project/polls_class/templates/polls/index.html
{% if latest_question_list %}
    <ul>
    {% for question in latest_question_list %}
        <li><a href="{% url 'polls_class:detail' question.id %}">{{ question.question_text }}</a></li>
    {% endfor %}
    </ul>
{% else %}
    <p>No polls are available.</p>
{% endif %}

first_project/polls_class/templates/polls/results.html
<h1>{{ question.question_text }}</h1>

<ul>
    {% for choice in question.choice_set.all %}
        <li>{{ choice.choice_text }} ---> {{ choice.votes }} vote{{ choice.votes|pluralize }}</li>
    {% endfor %}
</ul>

<a href="{% url 'polls_class:detail' question.id %}">Vote again?</a>